// app/layout.js
import "./globals.css";
import AOSProvider from "./components/AosProvider";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="de">
      <body  suppressHydrationWarning>
      <AOSProvider>
        <Header/>
        {children}
        </AOSProvider>
        <Footer/>
      </body>
    </html>
  );
}
